import { seedData } from './dataSeed';
import { calculateShipmentTotals, downloadTextFile } from './helpers';
import type { ERPApi } from '../types/api';
import type { CatalogItem, DashboardStats, DocumentRecord, InventoryItem, InventoryMovement, ProductionOrder, Shipment, TemplateRecord } from '../types/entities';
const storageKey='mapco-erp-local-v8';
function ensureLocalBootstrap(){ const existing=localStorage.getItem(storageKey); if(!existing){ localStorage.setItem(storageKey, JSON.stringify(seedData)); } }
function readStore(){ ensureLocalBootstrap(); return JSON.parse(localStorage.getItem(storageKey) ?? JSON.stringify(seedData)); }
function writeStore(data:unknown){ localStorage.setItem(storageKey, JSON.stringify(data)); }
function createId(prefix:string){ return `${prefix}-${Math.random().toString(36).slice(2,8)}`; }
function csv(rows:Record<string,unknown>[], filename:string){ const headers=Object.keys(rows[0] ?? {}); const content='\ufeff'+[headers.join(','),...rows.map((row)=>headers.map((header)=>JSON.stringify(row[header] ?? '')).join(','))].join('\n'); return downloadTextFile(filename, content); }
function parseLines(order:Partial<ProductionOrder>){ try{ return JSON.parse(order.materialLinesJson || '[]'); }catch{ return []; } }
function calcOrderCost(order:Partial<ProductionOrder>){ const total=parseLines(order).reduce((sum:number,line:any)=>sum+Number(line.totalCost||0),0); return Number((total || Number(order.cost||0)).toFixed(2)); }
function restoreOrderStock(store:any, orderId:string){ const movements=(store.inventoryMovements ?? []).filter((m:InventoryMovement)=>m.productionOrderId===orderId); for(const movement of movements){ const item=store.inventory.find((i:InventoryItem)=>i.id===movement.itemId); if(item && movement.type==='out'){ item.quantity=Number(item.quantity||0)+Number(movement.quantity||0); item.totalValue=item.quantity*item.unitCost; } }
 store.inventoryMovements=(store.inventoryMovements ?? []).filter((m:InventoryMovement)=>m.productionOrderId!==orderId); }
function applyOrderStock(store:any, order:ProductionOrder){ const lines=parseLines(order); for(const line of lines){ const item=store.inventory.find((i:InventoryItem)=>i.id===line.inventoryItemId); if(!item) continue; const qty=Number(line.quantity||0); item.quantity=Math.max(0,Number(item.quantity||0)-qty); item.totalValue=item.quantity*item.unitCost; store.inventoryMovements=[{id:createId('MOV'),itemId:item.id,itemName:item.itemName,type:'out',quantity:qty,date:order.startDate,notes:`صرف تلقائي لأمر الإنتاج ${order.orderNo} - ${line.componentType}`,productionOrderId:order.id},...(store.inventoryMovements ?? [])]; } }
function normalizeShipment(payload:any){ const customsRate=Number(payload.customsRate ?? 0.075); const vatRate=Number(payload.vatRate ?? 0.15); return {...payload,currency:payload.currency || 'SAR',exchangeRate:Number(payload.exchangeRate||1),customsRate,vatRate,documentsJson:payload.documentsJson || JSON.stringify([{name:'Commercial Invoice',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Packing List',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Bill of Lading',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Certificate of Origin',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Customs Papers',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''}]),...calculateShipmentTotals(payload.shipmentValue,payload.shippingCost,customsRate,vatRate)}; }
function localApi():ERPApi{ return {
 async bootstrap(){ ensureLocalBootstrap(); return readStore(); },
 async getCompanyProfile(){ return readStore().companyProfile; },
 async updateCompanyProfile(payload){ const store=readStore(); store.companyProfile={...store.companyProfile,...payload,updatedAt:new Date().toISOString()}; writeStore(store); return store.companyProfile; },
 async getDashboardStats(){ const store=readStore(); const shipmentsValue=store.shipments.reduce((sum:number,s:Shipment)=>sum+s.total,0); const customsValue=store.shipments.reduce((sum:number,s:Shipment)=>sum+s.customs,0); const inventoryValue=store.inventory.reduce((sum:number,s:InventoryItem)=>sum+s.totalValue,0); const productionCost=store.productionOrders.reduce((sum:number,s:ProductionOrder)=>sum+s.cost,0); const ordersCount=store.productionOrders.length; const missingDocuments=store.documents.filter((d:DocumentRecord)=>d.status==='ناقص').length; const lowStockItems=store.inventory.filter((i:InventoryItem)=>i.quantity<=i.reorderLevel).length; return {shipmentsValue,customsValue,inventoryValue,productionCost,ordersCount,missingDocuments,lowStockItems}; },
 async getShipments(){ return readStore().shipments; },
 async createShipment(payload){ const store=readStore(); const record={...normalizeShipment(payload),id:createId('SHP')}; store.shipments.unshift(record); writeStore(store); return record; },
 async updateShipment(id,payload){ const store=readStore(); const index=store.shipments.findIndex((item:Shipment)=>item.id===id); const merged=normalizeShipment({...store.shipments[index],...payload}); store.shipments[index]=merged; writeStore(store); return merged; },
 async deleteShipment(id){ const store=readStore(); store.shipments=store.shipments.filter((item:Shipment)=>item.id!==id); writeStore(store); },
 async getInventory(){ return readStore().inventory; },
 async createInventoryItem(payload){ const store=readStore(); const record={...payload,id:createId('ITM'), totalValue: Number(payload.quantity||0)*Number(payload.unitCost||0)}; store.inventory.unshift(record); writeStore(store); return record; },
 async updateInventoryItem(id,payload){ const store=readStore(); const index=store.inventory.findIndex((item:InventoryItem)=>item.id===id); const merged={...store.inventory[index],...payload}; merged.totalValue=Number(merged.quantity||0)*Number(merged.unitCost||0); store.inventory[index]=merged; writeStore(store); return merged; },
 async deleteInventoryItem(id){ const store=readStore(); store.inventory=store.inventory.filter((item:InventoryItem)=>item.id!==id); writeStore(store); },
 async getInventoryMovements(){ return readStore().inventoryMovements ?? []; },
 async createInventoryMovement(payload){ const store=readStore(); const item=store.inventory.find((i:InventoryItem)=>i.id===payload.itemId); if(!item) throw new Error('Item not found'); const qty=Number(payload.quantity); if(payload.type==='in') item.quantity+=qty; else if(payload.type==='out') item.quantity=Math.max(0,item.quantity-qty); else item.quantity=qty; item.totalValue=item.quantity*item.unitCost; const record:InventoryMovement={...payload,itemName:item.itemName,id:createId('MOV'),productionOrderId:payload.productionOrderId ?? ''}; store.inventoryMovements=[record,...(store.inventoryMovements ?? [])]; writeStore(store); return record; },
 async getProductionOrders(){ return readStore().productionOrders; },
 async createProductionOrder(payload){ const store=readStore(); const record:ProductionOrder={...payload,id:createId('PRD'),materialLinesJson:payload.materialLinesJson || '[]',stockLinked:payload.stockLinked ?? true,cost:calcOrderCost(payload),material:parseLines(payload).map((l:any)=>l.componentType).join(' + ') || payload.material}; store.productionOrders.unshift(record); if(record.stockLinked) applyOrderStock(store,record); writeStore(store); return record; },
 async updateProductionOrder(id,payload){ const store=readStore(); restoreOrderStock(store,id); const index=store.productionOrders.findIndex((item:ProductionOrder)=>item.id===id); const merged:ProductionOrder={...store.productionOrders[index],...payload}; merged.cost=calcOrderCost(merged); merged.material=parseLines(merged).map((l:any)=>l.componentType).join(' + ') || merged.material; store.productionOrders[index]=merged; if(merged.stockLinked) applyOrderStock(store,merged); writeStore(store); return merged; },
 async deleteProductionOrder(id){ const store=readStore(); restoreOrderStock(store,id); store.productionOrders=store.productionOrders.filter((item:ProductionOrder)=>item.id!==id); writeStore(store); },
 async getDocuments(){ return readStore().documents; },
 async createDocument(payload){ const store=readStore(); const record:DocumentRecord={...payload,id:createId('DOC')}; store.documents.unshift(record); writeStore(store); return record; },
 async updateDocument(id,payload){ const store=readStore(); const index=store.documents.findIndex((item:DocumentRecord)=>item.id===id); const merged={...store.documents[index],...payload}; store.documents[index]=merged; writeStore(store); return merged; },
 async deleteDocument(id){ const store=readStore(); store.documents=store.documents.filter((item:DocumentRecord)=>item.id!==id); writeStore(store); },
 async getItems(){ return readStore().items ?? []; },
 async createItem(payload){ const store=readStore(); const record:CatalogItem={...payload,id:createId('CAT')}; store.items=[record,...(store.items ?? [])]; writeStore(store); return record; },
 async updateItem(id,payload){ const store=readStore(); const index=(store.items ?? []).findIndex((item:CatalogItem)=>item.id===id); const merged={...store.items[index],...payload}; store.items[index]=merged; writeStore(store); return merged; },
 async deleteItem(id){ const store=readStore(); store.items=(store.items ?? []).filter((item:CatalogItem)=>item.id!==id); writeStore(store); },
 async getTemplates(){ return readStore().templates ?? []; },
 async createTemplate(payload){ const store=readStore(); const record:TemplateRecord={...payload,id:createId('TPL')}; store.templates=[record,...(store.templates ?? [])]; writeStore(store); return record; },
 async updateTemplate(id,payload){ const store=readStore(); const index=(store.templates ?? []).findIndex((item:TemplateRecord)=>item.id===id); const merged={...store.templates[index],...payload}; store.templates[index]=merged; writeStore(store); return merged; },
 async deleteTemplate(id){ const store=readStore(); store.templates=(store.templates ?? []).filter((item:TemplateRecord)=>item.id!==id); writeStore(store); },
 async exportReport(kind){ const store=readStore(); const map:any={shipments:'shipments',inventory:'inventory',production:'productionOrders',documents:'documents',items:'items',templates:'templates'}; return professionalXls(store[map[kind]] ?? [], `${kind}-professional-report.xls`, `${kind} report`); },
 async exportReportExcel(kind){ const store=readStore(); const map:any={shipments:'shipments',inventory:'inventory',production:'productionOrders',documents:'documents',items:'items',templates:'templates'}; return professionalXls(store[map[kind]] ?? [], `${kind}-professional-report.xls`, `${kind} report`); },
 async exportReportPdf(kind){ const store=readStore(); const map:any={shipments:'shipments',inventory:'inventory',production:'productionOrders',documents:'documents',items:'items',templates:'templates'}; return professionalPdfFallback(store[map[kind]] ?? [], `${kind}-professional-report.html`, `${kind} report`); },
 async backupStatus(){ const store=readStore(); return {databasePath:'LocalStorage fallback',exists:true,sizeBytes:new Blob([JSON.stringify(store)]).size,records:{shipments:store.shipments?.length ?? 0,inventory:store.inventory?.length ?? 0,productionOrders:store.productionOrders?.length ?? 0,documents:store.documents?.length ?? 0,items:store.items?.length ?? 0,templates:store.templates?.length ?? 0}}; },
 async createBackup(){ const store=readStore(); const content=JSON.stringify({format:'MahabatAlfanERPBackupFallback',createdAt:new Date().toISOString(),data:store},null,2); downloadTextFile(`mahabat-alfan-backup-${new Date().toISOString().slice(0,10)}.json`,content); return {canceled:false,path:'تم تنزيل نسخة احتياطية من المتصفح',createdAt:new Date().toISOString()}; },
 async restoreBackup(){ alert('الاستيراد الحقيقي متاح في نسخة Electron Desktop فقط.'); return {canceled:true,path:''}; }
};}
export const api:ERPApi = window.mapco?.api ?? localApi();
