import { useEffect, useState } from 'react';
import type { Shipment, ShipmentDocumentLink } from '../../types/entities';
import { ActionButton } from '../ui/ActionButton';
import { formatCurrency, todayISO } from '../../lib/helpers';

type EditableShipment=Omit<Shipment,'id'|'customs'|'vat'|'total'>;
const defaultDocs:ShipmentDocumentLink[]=[{name:'Commercial Invoice',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Packing List',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Bill of Lading',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Certificate of Origin',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Customs Papers',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''},{name:'Insurance Documents',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''}];
const initialState:EditableShipment={shipmentNo:'',supplier:'',country:'',port:'',eta:todayISO(),shippingCost:0,shipmentValue:0,notes:'',clearanceStatus:'بانتظار الوصول',status:'قيد الشحن',invoiceNo:'',purchaseOrderNo:'',blNo:'',containerNo:'',shippingLine:'',incoterm:'CIF',currency:'SAR',exchangeRate:1,customsRate:0.075,vatRate:0.15,driveFolderUrl:'',documentsJson:JSON.stringify(defaultDocs)};
function parseDocs(value?:string){ try{ const rows=JSON.parse(value || '[]'); return rows.length ? rows : defaultDocs; }catch{ return defaultDocs; } }
export function ShipmentForm({initial,onSubmit}:{initial?:Shipment|null;onSubmit:(payload:EditableShipment)=>Promise<void>}){
 const [form,setForm]=useState<EditableShipment>(initial ?? initialState);
 const [docs,setDocs]=useState<ShipmentDocumentLink[]>(parseDocs(initial?.documentsJson));
 useEffect(()=>{ const next=initial ? {...initial,documentsJson:initial.documentsJson || JSON.stringify(defaultDocs)} : initialState; setForm(next); setDocs(parseDocs(next.documentsJson)); },[initial]);
 const shipmentValue=Number(form.shipmentValue||0); const shippingCost=Number(form.shippingCost||0); const customsRate=Number(form.customsRate ?? 0.075); const vatRate=Number(form.vatRate ?? 0.15); const customs=(shipmentValue+shippingCost)*customsRate; const vat=(shipmentValue+shippingCost+customs)*vatRate; const total=shipmentValue+shippingCost+customs+vat;
 function updateDoc(index:number,patch:Partial<ShipmentDocumentLink>){ setDocs((prev)=>prev.map((doc,i)=>i===index?{...doc,...patch}:doc)); }
 return <form className="space-y-5" onSubmit={(e)=>{e.preventDefault(); void onSubmit({...form,documentsJson:JSON.stringify(docs)});}}>
  <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
   {[['shipmentNo','رقم الشحنة'],['supplier','المورد'],['country','بلد الشحن'],['port','ميناء الوصول'],['eta','ETA'],['invoiceNo','رقم الفاتورة'],['purchaseOrderNo','رقم أمر الشراء'],['blNo','رقم بوليصة الشحن B/L'],['containerNo','رقم الحاوية'],['shippingLine','الخط الملاحي'],['incoterm','Incoterm'],['currency','العملة']].map(([key,label])=><div key={key}><label className="label">{label}</label><input className="input" type={key==='eta'?'date':'text'} value={String((form as Record<string,unknown>)[key] ?? '')} onChange={(e)=>setForm((prev)=>({...prev,[key]:e.target.value}))} /></div>)}
   <div><label className="label">قيمة الشحنة</label><input className="input" type="number" step="0.01" value={form.shipmentValue} onChange={(e)=>setForm((prev)=>({...prev,shipmentValue:Number(e.target.value)}))} /></div>
   <div><label className="label">تكلفة الشحن</label><input className="input" type="number" step="0.01" value={form.shippingCost} onChange={(e)=>setForm((prev)=>({...prev,shippingCost:Number(e.target.value)}))} /></div>
   <div><label className="label">سعر الصرف</label><input className="input" type="number" step="0.0001" value={form.exchangeRate ?? 1} onChange={(e)=>setForm((prev)=>({...prev,exchangeRate:Number(e.target.value)}))} /></div>
   <div><label className="label">نسبة الجمارك</label><input className="input" type="number" step="0.001" value={form.customsRate ?? 0.075} onChange={(e)=>setForm((prev)=>({...prev,customsRate:Number(e.target.value)}))} /></div>
   <div><label className="label">نسبة الضريبة VAT</label><input className="input" type="number" step="0.001" value={form.vatRate ?? 0.15} onChange={(e)=>setForm((prev)=>({...prev,vatRate:Number(e.target.value)}))} /></div>
   <div><label className="label">الحالة</label><select className="input" value={form.status} onChange={(e)=>setForm((prev)=>({...prev,status:e.target.value}))}><option>قيد الشحن</option><option>في انتظار التحصيل</option><option>تحت التخليص</option><option>وصلت</option><option>مكتمل</option></select></div>
   <div><label className="label">حالة التخليص</label><input className="input" value={form.clearanceStatus} onChange={(e)=>setForm((prev)=>({...prev,clearanceStatus:e.target.value}))} /></div>
   <div className="md:col-span-3"><label className="label">رابط فولدر Google Drive لمستندات الشحنة</label><input className="input" dir="ltr" placeholder="https://drive.google.com/drive/folders/..." value={form.driveFolderUrl ?? ''} onChange={(e)=>setForm((prev)=>({...prev,driveFolderUrl:e.target.value}))} /></div>
   <div className="md:col-span-3"><label className="label">ملاحظات الشحنة</label><textarea className="input min-h-24" value={form.notes ?? ''} onChange={(e)=>setForm((prev)=>({...prev,notes:e.target.value}))} /></div>
  </div>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">الجمارك</div><div className="text-lg font-bold">{formatCurrency(customs)} SAR</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-sm text-slate-500">VAT</div><div className="text-lg font-bold">{formatCurrency(vat)} SAR</div></div><div className="rounded-2xl bg-mapco-50 p-4 md:col-span-2"><div className="text-sm text-mapco-700">إجمالي Landed Cost</div><div className="text-xl font-bold text-mapco-900">{formatCurrency(total)} SAR</div></div></div>
  <div className="rounded-3xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-bold text-slate-900">مستندات الشحنة وروابط Drive</h3><p className="text-sm text-slate-500">مستوحاة من ملف متابعة الشحنات Excel: رقم الشحنة، التاريخ، الحالة، وفتح المستند.</p></div><ActionButton variant="secondary" onClick={()=>setDocs((prev)=>[...prev,{name:'مستند جديد',status:'ناقص',driveUrl:'',receiveDate:'',remarks:''}])}>إضافة مستند</ActionButton></div><div className="space-y-3">{docs.map((doc,index)=><div key={`${doc.name}-${index}`} className="grid grid-cols-1 gap-3 rounded-2xl bg-slate-50 p-3 md:grid-cols-[1fr_.7fr_.7fr_1.4fr_1fr]"><div><label className="label">المستند</label><input className="input" value={doc.name} onChange={(e)=>updateDoc(index,{name:e.target.value})} /></div><div><label className="label">الحالة</label><select className="input" value={doc.status} onChange={(e)=>updateDoc(index,{status:e.target.value as ShipmentDocumentLink['status']})}><option>مكتمل</option><option>ناقص</option><option>قيد المراجعة</option></select></div><div><label className="label">تاريخ الاستلام</label><input className="input" type="date" value={doc.receiveDate ?? ''} onChange={(e)=>updateDoc(index,{receiveDate:e.target.value})} /></div><div><label className="label">رابط Drive</label><input className="input" dir="ltr" value={doc.driveUrl ?? ''} onChange={(e)=>updateDoc(index,{driveUrl:e.target.value})} /></div><div><label className="label">ملاحظات</label><input className="input" value={doc.remarks ?? ''} onChange={(e)=>updateDoc(index,{remarks:e.target.value})} /></div></div>)}</div></div>
  <div className="flex justify-end"><ActionButton type="submit">حفظ الشحنة</ActionButton></div>
 </form>;
}
