name: Build ERP EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd mapco-erp-execution
          npm install

      - name: Build project
        run: |
          cd mapco-erp-execution
          npm run dist

      - name: Show release files
        run: |
          cd mapco-erp-execution
          dir release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ERP-EXE
          path: mapco-erp-execution/release/**
